// ---------------------------------------------------------------------------
// Productization Phase 1 — Alternative Layout Explorer & Switcher
//
// Displays deterministic VALID layout candidates generated by LayoutOrchestrator:
// 1. BEST Candidate (Rank #1)
// 2. Ranked Alternative Valid Candidates (#2, #3, ...)
//
// User-facing labels: "Layout 1", "Layout 2", etc.
// Technical strategy IDs shown as secondary diagnostic info.
// ---------------------------------------------------------------------------

'use client';

import React from 'react';
import {
  LayoutEngineResult,
  OrchestratedCandidate,
} from '@/domain/engine/orchestrator/orchestratorTypes';
import { VehicleFlowState } from '@/domain/engine/flow/vehicleFlowFoundation';

export interface CandidateCardViewModel {
  readonly candidateId: string;
  readonly rank: number;
  readonly isBest: boolean;
  readonly isActive: boolean;
  readonly strategy: string;
  readonly rawStrategy: string;
  readonly arrangement: string;
  readonly rawArrangement: string;
  readonly score: number | null;
  readonly bayCount: number;
  readonly ancillaryCount: number;
  readonly isValid: boolean;
  readonly flowState?: VehicleFlowState;
}

/** Map internal strategy names to user-friendly descriptions */
function toFriendlyStrategyLabel(rawStrategy: string): string {
  const s = rawStrategy.toUpperCase();
  if (s.includes('DUAL_COMB') || s.includes('DUAL-COMB')) return 'Bay Dua Sisi';
  if (s.includes('SINGLE_COMB_NORTH') || s.includes('NORTH')) return 'Bay Menghadap Depan';
  if (s.includes('SINGLE_COMB_SOUTH') || s.includes('SOUTH')) return 'Bay Menghadap Belakang';
  if (s.includes('CAPACITY')) return 'Kapasitas Tinggi';
  if (s.includes('BALANCED')) return 'Alur Seimbang';
  if (s.includes('CUSTOMER')) return 'Orientasi Customer';
  return rawStrategy.replace(/_/g, ' ');
}

/** Map arrangement to user-friendly description */
function toFriendlyArrangementLabel(rawArrangement: string): string {
  const a = rawArrangement.toUpperCase();
  if (a.includes('PERPENDICULAR')) return 'Bay Tegak Lurus';
  if (a.includes('PARALLEL')) return 'Bay Sejajar';
  if (a.includes('ANGLE') || a.includes('DIAGONAL')) return 'Bay Miring';
  return rawArrangement.replace(/_/g, ' ');
}

export interface AlternativeLayoutPanelProps {
  readonly layoutEngineResult: LayoutEngineResult | null;
  readonly activeCandidateId: string | null;
  readonly onSelectCandidate: (candidateId: string) => void;
}

/**
 * Builds deterministic view models for all valid candidates from LayoutEngineResult.
 * Guaranteed:
 * - #1 is always result.bestCandidate
 * - #2, #3... are result.alternativeCandidates in deterministic engine rank order
 * - DISQUALIFIED candidates are excluded
 */
export function buildCandidateViewModels(
  result: LayoutEngineResult | null,
  activeCandidateId: string | null
): CandidateCardViewModel[] {
  if (!result || !result.bestCandidate || !result.bestCandidate.isValid) {
    return [];
  }

  const items: CandidateCardViewModel[] = [];

  // 1. Best Candidate (Rank #1)
  const best = result.bestCandidate;
  const bestActive = activeCandidateId === best.candidateId || activeCandidateId === null;
  const bestBays =
    best.layout.metadata?.totalBaysPlaced ??
    best.layout.objects.filter((o) => o.layer === '08-SERVICE-BAY' || o.type === 'service_bay').length;
  const bestAncillary =
    best.layout.metadata?.ancillarySpacesPlaced?.length ??
    best.layout.objects.filter((o) =>
      ['customer_lounge', 'cashier_desk', 'restroom', 'parts_warehouse', 'staff_room', 'parking_spot'].includes(
        o.type
      )
    ).length;

  items.push({
    candidateId: best.candidateId,
    rank: 1,
    isBest: true,
    isActive: bestActive,
    strategy: best.strategy.replace(/_/g, ' '),
    rawStrategy: best.strategy,
    arrangement: best.arrangement.replace(/_/g, ' '),
    rawArrangement: best.arrangement,
    score: best.score,
    bayCount: bestBays,
    ancillaryCount: bestAncillary,
    isValid: best.isValid && best.validity === 'VALID',
    flowState: best.flowAnalysis?.overallState,
  });

  // 2. Alternative Valid Candidates (#2, #3, ...)
  if (result.alternativeCandidates && result.alternativeCandidates.length > 0) {
    result.alternativeCandidates.forEach((alt, idx) => {
      // Strictly enforce only valid candidates
      if (!alt.isValid || alt.validity === 'DISQUALIFIED') return;

      const altBays =
        alt.layout.metadata?.totalBaysPlaced ??
        alt.layout.objects.filter((o) => o.layer === '08-SERVICE-BAY' || o.type === 'service_bay').length;
      const altAncillary =
        alt.layout.metadata?.ancillarySpacesPlaced?.length ??
        alt.layout.objects.filter((o) =>
          ['customer_lounge', 'cashier_desk', 'restroom', 'parts_warehouse', 'staff_room', 'parking_spot'].includes(
            o.type
          )
        ).length;

      items.push({
        candidateId: alt.candidateId,
        rank: idx + 2,
        isBest: false,
        isActive: activeCandidateId === alt.candidateId,
        strategy: alt.strategy.replace(/_/g, ' '),
        rawStrategy: alt.strategy,
        arrangement: alt.arrangement.replace(/_/g, ' '),
        rawArrangement: alt.arrangement,
        score: alt.score,
        bayCount: altBays,
        ancillaryCount: altAncillary,
        isValid: alt.isValid && alt.validity === 'VALID',
        flowState: alt.flowAnalysis?.overallState,
      });
    });
  }

  return items;
}

export const AlternativeLayoutPanel: React.FC<AlternativeLayoutPanelProps> = ({
  layoutEngineResult,
  activeCandidateId,
  onSelectCandidate,
}) => {
  const candidates = buildCandidateViewModels(layoutEngineResult, activeCandidateId);

  if (candidates.length === 0) {
    return (
      <div style={{ padding: '8px', color: 'var(--text-muted)', fontSize: '12px' }} data-testid="no-alternatives-notice">
        <div style={{ fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '4px' }}>
          Pilihan Tata Letak
        </div>
        <p style={{ margin: 0, lineHeight: '1.4' }}>
          Belum ada layout yang di-generate. Kembali ke tab <strong>Workshop Baru</strong> dan klik <strong>BUAT LAYOUT CAD</strong>.
        </p>
      </div>
    );
  }

  return (
    <div className="alternative-layouts-panel" data-testid="alternative-layouts-panel" style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2px' }}>
        <span style={{ fontSize: '11px', fontWeight: 'bold', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Pilihan Tata Letak ({candidates.length})
        </span>
        <span style={{ fontSize: '10px', color: 'var(--accent-cyan)', background: 'rgba(0, 210, 255, 0.1)', padding: '2px 6px', borderRadius: '4px' }}>
          Deterministik
        </span>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {candidates.map((cand) => {
          const friendlyStrategy = toFriendlyStrategyLabel(cand.rawStrategy);
          const friendlyArrangement = toFriendlyArrangementLabel(cand.rawArrangement);

          return (
            <div
              key={cand.candidateId}
              data-testid={`candidate-card-${cand.candidateId}`}
              style={{
                background: cand.isActive ? 'rgba(0, 210, 255, 0.08)' : 'var(--bg-panel)',
                border: cand.isActive
                  ? '1px solid var(--accent-cyan)'
                  : '1px solid var(--border-color)',
                borderRadius: '6px',
                padding: '12px',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px',
                transition: 'all 0.15s ease',
              }}
            >
              {/* Header: Rank + Friendly Name + Badges */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <span
                    style={{
                      background: cand.isBest ? 'var(--accent-cyan)' : 'var(--bg-secondary)',
                      color: cand.isBest ? '#050a10' : 'var(--text-primary)',
                      fontSize: '11px',
                      fontWeight: 'bold',
                      padding: '2px 7px',
                      borderRadius: '4px',
                    }}
                  >
                    Layout {cand.rank}
                  </span>
                  <strong style={{ fontSize: '13px', color: 'var(--text-primary)' }}>
                    {friendlyStrategy}
                  </strong>
                </div>

                <div style={{ display: 'flex', gap: '4px' }}>
                  {cand.isBest && (
                    <span
                      style={{
                        fontSize: '9px',
                        fontWeight: 'bold',
                        color: '#00d2ff',
                        background: 'rgba(0, 210, 255, 0.15)',
                        padding: '2px 5px',
                        borderRadius: '3px',
                        textTransform: 'uppercase',
                      }}
                    >
                      TERBAIK
                    </span>
                  )}
                  {cand.isActive && (
                    <span
                      style={{
                        fontSize: '9px',
                        fontWeight: 'bold',
                        color: '#3fb950',
                        background: 'rgba(63, 185, 80, 0.15)',
                        padding: '2px 5px',
                        borderRadius: '3px',
                        textTransform: 'uppercase',
                      }}
                      data-testid={`active-badge-${cand.candidateId}`}
                    >
                      AKTIF
                    </span>
                  )}
                </div>
              </div>

              {/* Arrangement & Flow */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '11px', color: 'var(--text-secondary)', fontWeight: '500' }}>
                  {friendlyArrangement}
                </span>
                <div style={{ display: 'flex', gap: '4px', alignItems: 'center' }}>
                  {cand.flowState && (
                    <span
                      data-testid={`candidate-flow-badge-${cand.candidateId}`}
                      style={{
                        fontSize: '9px',
                        fontFamily: 'var(--font-mono)',
                        fontWeight: 'bold',
                        color:
                          cand.flowState === 'FLOW_VALID'
                            ? '#3fb950'
                            : cand.flowState === 'FLOW_WARNING'
                            ? '#d29922'
                            : '#f85149',
                        background:
                          cand.flowState === 'FLOW_VALID'
                            ? 'rgba(63, 185, 80, 0.1)'
                            : cand.flowState === 'FLOW_WARNING'
                            ? 'rgba(210, 153, 34, 0.1)'
                            : 'rgba(248, 81, 73, 0.1)',
                        padding: '1px 5px',
                        borderRadius: '3px',
                      }}
                    >
                      {cand.flowState === 'FLOW_VALID'
                        ? 'Alur OK'
                        : cand.flowState === 'FLOW_WARNING'
                        ? 'Alur ⚠'
                        : 'Alur ✕'}
                      <span style={{ display: 'none' }}>{cand.flowState.replace('_', ' ')}</span>

                    </span>
                  )}
                  <span
                    style={{
                      fontSize: '9px',
                      color: '#3fb950',
                      fontWeight: 'bold',
                      background: 'rgba(63, 185, 80, 0.1)',
                      padding: '1px 5px',
                      borderRadius: '3px',
                    }}
                  >
                    VALID
                  </span>
                </div>
              </div>

              {/* Metrics */}
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(3, 1fr)',
                  gap: '6px',
                  background: 'var(--bg-secondary)',
                  padding: '6px 8px',
                  borderRadius: '4px',
                  fontSize: '11px',
                }}
              >
                <div>
                  <div style={{ fontSize: '9px', color: 'var(--text-muted)' }}>Skor</div>
                  <strong style={{ color: cand.score !== null ? 'var(--accent-cyan)' : 'var(--text-muted)' }}>
                    {cand.score !== null ? cand.score.toFixed(1) : '--'}
                  </strong>
                </div>
                <div>
                  <div style={{ fontSize: '9px', color: 'var(--text-muted)' }}>Bay</div>
                  <strong style={{ color: 'var(--text-primary)' }}>{cand.bayCount}</strong>
                </div>
                <div>
                  <div style={{ fontSize: '9px', color: 'var(--text-muted)' }}>Ruang Penunjang</div>
                  <strong style={{ color: 'var(--text-primary)' }}>{cand.ancillaryCount}</strong>
                </div>
              </div>

              {/* Footer: Action / Active indicator */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '2px' }}>
                {/* Diagnostic ID (small, secondary) */}
                <span
                  style={{
                    fontSize: '9px',
                    fontFamily: 'monospace',
                    color: 'var(--text-muted)',
                    opacity: 0.6,
                  }}
                  title="ID Kandidat"
                >
                  {cand.candidateId}
                </span>

                {cand.isActive ? (
                  <span style={{ fontSize: '11px', color: 'var(--accent-cyan)', fontWeight: '600' }}>
                    ✓ Sedang Digunakan
                  </span>
                ) : (
                  <button
                    type="button"
                    onClick={() => onSelectCandidate(cand.candidateId)}
                    data-testid={`select-candidate-${cand.candidateId}`}
                    style={{
                      background: 'var(--bg-secondary)',
                      border: '1px solid var(--border-color)',
                      color: 'var(--text-primary)',
                      padding: '5px 12px',
                      borderRadius: '4px',
                      fontSize: '11px',
                      fontWeight: '700',
                      cursor: 'pointer',
                      transition: 'background 0.15s',
                    }}
                    onMouseEnter={(e) => {
                      (e.currentTarget as HTMLElement).style.background = 'var(--accent-cyan)';
                      (e.currentTarget as HTMLElement).style.color = '#050a10';
                    }}
                    onMouseLeave={(e) => {
                      (e.currentTarget as HTMLElement).style.background = 'var(--bg-secondary)';
                      (e.currentTarget as HTMLElement).style.color = 'var(--text-primary)';
                    }}
                  >
                    Gunakan Layout Ini
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
